language: python
python: 
    - 3.6
before_install:
    - python --version
    - pip install -U pip
    - pip install -r requirements.txt
script:
    - pytest --cov =com com/tiago/test/test_app_web_start.py